language: php

php:
  - 5.2
  - 5.3
  - 5.4
  - 5.5
  - 5.6

before_script:
  - sh -c "if [ '$TRAVIS_PHP_VERSION' != '5.2' ]; then composer global require 'phpunit/phpunit=3.7.33'; fi"
  - sh -c "if [ '$TRAVIS_PHP_VERSION' != '5.2' ]; then ln -s ~/.composer/vendor/phpunit/phpunit/PHPUnit ./vendors/PHPUnit; fi"
  - git clone git://github.com/cakephp/cakephp ../cakephp && cd ../cakephp
  - mv ../CakePHP-DatabaseLog app/Plugin/DatabaseLog
  - chmod -R 777 ../cakephp/app/tmp
  - sh -c "mysql -e 'CREATE DATABASE cakephp_test;'"
  - echo "<?php
      class DATABASE_CONFIG {
      public \$test = array(
        'datasource' => 'Database/Mysql',
        'database' => 'cakephp_test',
        'host' => '0.0.0.0',
        'login' => 'travis',
        'persistent' => false,
      );
      }" > ../cakephp/app/Config/database.php

script:
  - ./lib/Cake/Console/cake test DatabaseLog AllTests --stderr

notifications:
  email: false